### ISSUE TITLE
Incorrect utf-8 charcters

### ISSUE THREAD

**Issue by ghost** [PaulaMigrate/NaliaEE#1]
Hopefully this is the place for reporting problems.

I found a small issue with incorrect utf-8 characters. Please see the incorrect apostrophes.

![dearnise](https://user-images.githubusercontent.com/2090214/37910115-0924c67a-310d-11e8-9dba-fee1ca495956.jpeg)

**Comment by PaulaMigrate** [comment]
Thank you
It was in the english tra file itself, I don't think iconv even touches it.
Should be corrected now
